name: check-diff
on: 
  push:
  pull_request:
    branches:
      - "main"
      - "develop"
    paths-ignore:
      - "docs/**"
      - "**.md"
env:
  WORKSPACE_PREFIX: $(echo $GITHUB_WORKSPACE |cut -d '/' -f 1-4)
  SLURM_PARTITION: llm_s

jobs:
  check-requirements:
    runs-on: [ubuntu-latest]
    steps:
    - name: mask env
      run: |
        echo "::add-mask::${{env.WORKSPACE_PREFIX}}"
    - uses: actions/checkout@v3
      with:
         fetch-depth: 2
    - name: check-requirements
      run: |
        echo "beging test"
        changed_files=$(git diff --name-only -r HEAD^1 HEAD)
        echo $changed_files
        git diff  HEAD^1 HEAD >> origin.log
        ls -al
        cat origin.log
        git diff
