name: demo-in-readme
on: 
  push:
    branches:
      - "debug/test"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths-ignore:
      - "docs/**"
      - "**.md"
     
env:
   DIR_PREFIX: ${{secrets.DIR_PREFIX}}

jobs:
  dataset-preparation:
    runs-on: [lmtest]
    steps:
    - uses: actions/checkout@v3
      with:
         fetch-depth: 2

    - name: raw-chinese-data
      run: |
        source activate internlm-env-test
        echo ${{ github.head_ref }}
        echo 'debuging'
        echo ${{ github.base_ref }}
        #git diff --name-only -r ${{ github.head_ref }} ${{ github.base_ref }}
        files=$(git diff --name-only -r HEAD^1 HEAD)
        echo $files
        if [[ $files =~ "runtime.txt" ]]; then
          echo 'pip install -r requirements/runtime.txt'
        elif [[ $files =~ "torch.txt"  ]]; then
          echo 'pip install -r requirements/torch.txt'
        else
          echo 'There is no new requirements'
        fi
           
        #sh ./ci_scripts/data/tokenizer_chinese.sh


  
  load-chat-model-in-hf:
    if: ${{ always() }}
    needs: dataset-preparation
    runs-on: [lmtest]
    steps:
    - uses: actions/checkout@v3

    - name: chat-model-in-hf
      run: |
        source activate internlm-env-test
        
        #srun -p llm2 python ./ci_scripts/model/demo_load_7B_chat_model.py
