name: debug-test
on: 
  push:
    branches:
      - "debug/test"
      - "new/tmp"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths-ignore:
      - "docs/**"
      - "**.md"
     
env:
  #new_k: $(echo $GITHUB_WORKSPACE |cut -d '/' -f 1-4)
  new_k: /mnt/petrelfs/qa-caif-cicd

jobs:
  dataset-preparation:
    runs-on: [lmtest]
    steps:
    - name: set env
      run: |
        echo "$new_k"
        echo "::add-mask::$new_k"
        echo "after mask"
        echo "$new_k"
        #dir_prefix=$(echo $GITHUB_WORKSPACE |cut -d '/' -f 1-4)/data
        #echo "NEW_PREFIX=$dir_prefix" >> "$GITHUB_ENV" 
        #echo "action_state=yellow" >> "$GITHUB_ENV"
     
    - uses: actions/checkout@v3
      with:
         fetch-depth: 2

    - name: raw-chinese-data
      #env:
         #new_k: "${{env.NEW_PREFIX}}"
      run: |
        echo "show action info"
        echo "github action is $GITHUB_ACTION"
        echo "GITHUB ACTOR is $GITHUB_ACTOR"
        echo "GITHUB_ACTOR_ID is $GITHUB_ACTOR_ID"
        echo "GITHUB_RUN_ID is $GITHUB_RUN_ID"
        echo "runid and jobname is: $GITHUB_RUN_ID-$GITHUB_JOB"
        source activate internlm-env-test
        echo "show env info"
        echo $GITHUB_WORKSPACE
        echo "${{env.NEW_PREFIX}}"
        files=$(git diff --name-only -r HEAD^1 HEAD)
        echo $files
        if [[ $files =~ "runtime.txt" ]]; then
          echo 'pip install -r requirements/runtime.txt'
        fi
        
        if [[ $files =~ "torch.txt"  ]]; then
          echo 'pip install -r requirements/torch.txt'
        fi
     
        echo "${{ env.action_state }}"
        #echo $new_k
        #echo "var test "
        #echo "${{env.new_k}}"
        #sh ./ci_scripts/data/tokenizer_chinese.sh


  
  load-chat-model-in-hf:
    if: ${{ always() }}
    needs: dataset-preparation
    runs-on: [lmtest]
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v3

    - name: chat-model-in-hf
      run: |
        #echo ${{ secrets.NEW_PREFIX }}        
        echo "show action info in child job"
        echo "github action is $GITHUB_ACTION"
        echo "GITHUB ACTOR is $GITHUB_ACTOR"
        echo "GITHUB_ACTOR_ID is $GITHUB_ACTOR_ID"
        echo "GITHUB_RUN_ID is $GITHUB_RUN_ID"
        tmpvar=$GITHUB_RUN_ID-$GITHUB_JOB
        echo $tmpvar
        echo "runid and jobname is: $GITHUB_RUN_ID-$GITHUB_JOB"
        echo "again.${{env.new_k}}"
        srun -p llm2 --job-name=$GITHUB_RUN_ID-$GITHUB_JOB sh ci_scripts/data/tmp.sh
        source activate internlm-env-test
        #sh ci_scripts/data/tmp.sh
    
    - name: chattwo
      run: |
        echo "runid and jobname is: $GITHUB_RUN_ID'_'$GITHUB_JOB"
        echo "something"
